=== alohaaloha/digital-signatures-and-xml-documents/GsApp/complete/schema/Akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
    targetNamespace="http://www.gradskaskupstina.gov/" elementFormDefault="qualified"
    xmlns:gov="http://www.gradskaskupstina.gov/">

    <xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd"/>

    <xs:element name="Akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element default="Akt" name="Naslov">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="DocumentId" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:choice maxOccurs="1" minOccurs="1">
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="Deo" type="gov:TDeo"/>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="Glava" type="gov:TGlava"/>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="Clan" type="gov:TClan"/>
                </xs:choice>
                <xs:element name="ZavrsniDeo" type="gov:TZavrsniDeo"/>
                <xs:element name="UserName" type="xs:string"/>
                <xs:element name="TimeStamp" type="xs:dateTime"/>
                <xs:element ref="ds:Signature" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TAmandmani">
        <xs:sequence>
            <xs:element name="PravniOsnov" type="gov:TReferenca" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Akt" type="gov:TReferenca" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Amandman" type="gov:TAmandman" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="Potpisnici" type="gov:TPotpisnici" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TAmandman">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="PredmetIzmene" type="gov:TReferenca" minOccurs="1" maxOccurs="1"/>
            <xs:element name="TipIzmene" type="gov:TTipIzmene" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Obrazlozenje" type="gov:TSemiStruktuiraniTekst" minOccurs="1"
                maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="TTipIzmene">
        <xs:restriction base="xs:string">
            <xs:enumeration value="izmena"/>
            <xs:enumeration value="dopuna"/>
            <xs:enumeration value="brisanje"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TDeo">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="2" name="Glava" type="gov:TGlava"/>
        </xs:sequence>
        <xs:attribute name="Naziv" type="xs:string"/>
        <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="TGlava">
        <xs:choice>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="Clan" type="gov:TClan"/>
            <xs:element maxOccurs="unbounded" minOccurs="2" name="Odeljak" type="gov:TOdeljak"/>
        </xs:choice>
        <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="Naziv" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="TOdeljak">
        <xs:choice>
            <xs:element maxOccurs="unbounded" minOccurs="2" name="Pododeljak" type="gov:TPododeljak"/>
            <xs:element maxOccurs="unbounded" name="Clan" type="gov:TClan"/>
        </xs:choice>
        <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="Naziv" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="TPododeljak">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="Clan" type="gov:TClan"/>
        </xs:sequence>
        <xs:attribute name="RednoSlovo" type="gov:TRednoSlovo" use="required"/>
        <xs:attribute name="Naziv" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType final="" name="TRednoSlovo">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
            <xs:pattern value="\p{Ll}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TClan">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="Stav" type="gov:TStav"/>
        </xs:sequence>
        <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="Naziv" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="TStav" mixed="false">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="Tekst" type="xs:string"/>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element minOccurs="2" maxOccurs="unbounded" name="Tacka" type="gov:TTacka"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="TTacka">
        <xs:sequence>
            <xs:element name="Sadrzaj" type="xs:string"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Podtacka">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="RedniBroj" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="TZavrsniDeo">
        <xs:sequence>
            <xs:element name="PrelazneOdredbe" type="gov:TGlava" minOccurs="0" maxOccurs="1"/>
            <xs:element name="ZavrsneOdredbe" type="gov:TGlava" minOccurs="0" maxOccurs="1"/>
            <xs:element name="Organ" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Broj" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Datum" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Potpisnik" type="gov:TPotpisnik" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TPotpisnici">
        <xs:sequence>
            <xs:element name="Potpisnik" type="gov:TPotpisnik" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TPotpisnik">
        <xs:sequence>
            <xs:element name="Titula" type="xs:string" minOccurs="0"/>
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!--  Atribut referenca na clan, clanove, stav, stavove, tacku ili tacke nekog akta.
            Ovi atributi nalaze se u elementu <referenca></referenca>.
            Validni oblici:
        <referenca ref_clanovi="5,6"></referenca>
    -->
    <xs:attributeGroup name="AGReferenca">
        <xs:attribute name="ref_akt" type="xs:string" use="optional" default="ovaj_akt"/>
        <xs:attribute name="ref_clanovi" type="gov:TNiz_referenci" use="optional"/>
        <xs:attribute name="ref_stavovi" type="gov:TNiz_referenci" use="optional"/>
        <xs:attribute name="ref_tacke" type="gov:TNiz_referenci" use="optional"/>
    </xs:attributeGroup>

    <!-- Tip reference. Prakticno element koji je string sa atributima iz grupe referenca -->
    <xs:complexType name="TReferenca">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attributeGroup ref="gov:AGReferenca"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Polustruktuirani tekst sa elementima referencama i datumima -->
    <xs:complexType name="TSemiStruktuiraniTekst" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Tekst">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Referenca" type="gov:TReferenca"/>
            <xs:element name="Datum" type="xs:date"/>
        </xs:choice>
    </xs:complexType>

    <!-- Izgled atributa reference. Moze biti sledeceg oblika
            Kao obican broj: 15
            Kao vise brojeva u obliku: 4,5,6
            Kao niz brojeva u obliku: [1-4]
            Kao vise nizova brojeva u obliku: [1-4],[6-7]    -->
    <xs:simpleType name="TNiz_referenci">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d+,?)+"/>
            <xs:pattern value="(\d+-\d+,?)+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== alohaaloha/digital-signatures-and-xml-documents/ArcApp/complete/data/akt1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Akt xmlns="http://www.gradskaskupstina.gov/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.gradskaskupstina.gov/ file:/C:/Users/FS-LB/Desktop/XMLProjekat/DJIT/Xbes/GsApp/complete/schema/Akt.xsd">
    <Naslov>Akt</Naslov>
    <Glava RedniBroj="50" Naziv="Naziv1">
        <Odeljak RedniBroj="50" Naziv="Naziv3">
            <Clan RedniBroj="50">
                <Stav>
                    <Sadrzaj/>
                </Stav>
                <Stav>
                    <Sadrzaj/>
                </Stav>
            </Clan>
            <Clan RedniBroj="50">
                <Stav>
                    <Sadrzaj/>
                </Stav>
                <Stav>
                    <Sadrzaj/>
                </Stav>
            </Clan>
        </Odeljak>
        <Odeljak RedniBroj="50" Naziv="Naziv9">
            <Clan RedniBroj="50">
                <Stav>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj0</Sadrzaj>
                    </Tacka>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj1</Sadrzaj>
                    </Tacka>
                </Stav>
                <Stav>
                    <Sadrzaj/>
                </Stav>
            </Clan>
            <Clan RedniBroj="50">
                <Stav>
                    <Sadrzaj/>
                </Stav>
                <Stav>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj2</Sadrzaj>
                    </Tacka>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj3</Sadrzaj>
                    </Tacka>
                </Stav>
            </Clan>
        </Odeljak>
    </Glava>
    <Glava RedniBroj="50" Naziv="Naziv15">
        <Odeljak RedniBroj="50" Naziv="Naziv17">
            <Clan RedniBroj="50">
                <Stav>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj4</Sadrzaj>
                    </Tacka>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj5</Sadrzaj>
                    </Tacka>
                </Stav>
                <Stav>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj6</Sadrzaj>
                    </Tacka>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj7</Sadrzaj>
                    </Tacka>
                </Stav>
            </Clan>
            <Clan RedniBroj="50">
                <Stav>
                    <Sadrzaj/>
                </Stav>
                <Stav>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj8</Sadrzaj>
                    </Tacka>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj9</Sadrzaj>
                    </Tacka>
                </Stav>
            </Clan>
        </Odeljak>
        <Odeljak RedniBroj="50" Naziv="Naziv23">
            <Clan RedniBroj="50">
                <Stav>
                    <Sadrzaj/>
                </Stav>
                <Stav>
                    <Sadrzaj/>
                </Stav>
            </Clan>
            <Clan RedniBroj="50">
                <Stav>
                    <Sadrzaj/>
                </Stav>
                <Stav>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj10</Sadrzaj>
                    </Tacka>
                    <Tacka RedniBroj="50">
                        <Sadrzaj>Sadrzaj11</Sadrzaj>
                    </Tacka>
                </Stav>
            </Clan>
        </Odeljak>
    </Glava>
    <ZavrsniDeo>
        <Organ>Organ0</Organ>
        <Broj>Broj0</Broj>
        <Datum>Datum0</Datum>
        <Potpisnik>
            <Ime>Ime0</Ime>
            <Prezime>Prezime0</Prezime>
        </Potpisnik>
    </ZavrsniDeo>
</Akt>

=== alohaaloha/digital-signatures-and-xml-documents/XMLSchema/AktZOIIDZOJPPIK.xml
<?xml version="1.0" encoding="UTF-8"?>
<Akt xmlns="http://www.gradskaskupstina.gov/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.gradskaskupstina.gov/ file:/C:/Users/FS-LB/Desktop/XMLProjekat/DJIT/Xbes/GsApp/complete/schema/Akt.xsd">
    <Naslov>Zakon o izmenama i dopunama zakona o javno-privatnom partnerstvu i koncesijama</Naslov>
    <Clan RedniBroj="1">
        <Stav><Sadrzaj>U Zakonu o javno-privatnom partnerstvu i koncesijama („Službeni glasnik RS”, broj 88/11), u članu 2. stav 1. posle reči: „partnerom” dodaju se reči: „radi realizacije projekata javno-privatnog partnerstva”.</Sadrzaj></Stav>
    </Clan>
    <Clan RedniBroj="2">
        <Stav><Sadrzaj>U <Referenca ref_akt="ZOJPPIK" ref_clanovi="4" ref_tacke="6">članu 4. tačka 6)</Referenca> reči: „može osnivati” zamenjuju se rečju: „osniva”.</Sadrzaj></Stav>
    </Clan>
    <Clan RedniBroj="3">
        <Stav><Sadrzaj>U <Referenca ref_akt="ZOJPPIK" ref_clanovi="7" ref_stavovi="2" ref_tacke="1">članu 7. stav 2. tačka 1)</Referenca> posle reči: „drugog dobra” dodaju se reči: „niti isključiva isporuka dobara”.</Sadrzaj></Stav>
        <Stav><Sadrzaj>U <Referenca ref_akt="ZOJPPIK" ref_clanovi="7" ref_stavovi="2" ref_tacke="3">stavu 2. tačka 3)</Referenca> reč: „projektovanje” i zapeta posle te reči brišu se.</Sadrzaj></Stav>
        <Stav><Sadrzaj>U <Referenca ref_akt="ZOJPPIK" ref_clanovi="7" ref_stavovi="2" ref_tacke="6">tački 6)</Referenca> posle reči: „između javnog i privatnog partnera” dodaje se zapeta i reči: „a naročito preuzimanje rizika tražnje ili rizika raspoloživosti objekta, usluge, infrastrukture i sl.”.</Sadrzaj></Stav>
    </Clan>
    <ZavrsniDeo>
        <Organ>Drzava0</Organ>
        <Broj>Broj0</Broj>
        <Datum>Datum0</Datum>
        <Potpisnik>
            <Ime>Ime0</Ime>
            <Prezime>Prezime0</Prezime>
        </Potpisnik>
    </ZavrsniDeo>
</Akt>
