=== alohaaloha/digital-signatures-and-xml-documents/GsApp/complete/schema/Users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.gradskaskupstina.gov/"
    targetNamespace="http://www.gradskaskupstina.gov/"
    elementFormDefault="qualified">
    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="User" type="User" minOccurs="1" maxOccurs="1"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="User">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="Username" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Ime" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Prezime" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="E-mail" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element name="Salt" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="Role" type="xs:string" minOccurs="1" maxOccurs="1" default="ROLE_GRADJANIN"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== alohaaloha/digital-signatures-and-xml-documents/XMLSchema/users1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns="http://www.gradskaskupstina.gov/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.gradskaskupstina.gov/ file:/C:/Users/FS-LB/Desktop/XMLProjekat/DJIT/Xbes/XMLSchema/Users.xsd">
	<User>
		<Username>rusija</Username>
		<Password>rusija</Password>
		<Ime>Radomir</Ime>
		<Prezime>Marinković</Prezime>
		<Salt>so</Salt>
		<Role>ROLE_PREDSEDNIK</Role>
	</User>
	<User>
		<Username>mitra</Username>
		<Password>mitra</Password>
		<Ime>Milan</Ime>
		<Prezime>Mitrić</Prezime>
		<Salt>so</Salt>
		<Role>ROLE_ODBORNIK</Role>
	</User>
	<User>
		<Username>roki</Username>
		<Password>roki</Password>
		<Ime>Nebojša</Ime>
		<Prezime>Popović</Prezime>
		<Salt>so</Salt>
		<Role>ROLE_GRADJANIN</Role>
	</User>
	<User>
		<Username>cho</Username>
		<Password>cho</Password>
		<Ime>Branislav</Ime>
		<Prezime>Čogić</Prezime>
		<Salt>so</Salt>
		<Role>ROLE_GRADJANIN</Role>
	</User>
</Users>
